
- name: Stop jira
  command: "{{ jira_install }}/bin/stop-jira.sh"   
  become: yes

- name: Tar install dir
  command: tar czf /tmp/jira_install_backup.tgz "{{ jira_install }}"
  args:
    creates: /tmp/jira_install_backup.tgz
  become: yes

- name: Tar home dir
  command: tar czf /tmp/jira_home_backup.tgz "{{ jira_home }}" 
  args:
    creates: /tmp/jira_home_backup.tgz
  become: yes

- name: pg_dump DB
  command: pg_dump -f /tmp/jira_db_backup.tar -F t -d {{ pgDatabase }} -U postgres
  args:
    creates: /tmp/jira_db_backup.tar
  become: yes
  become_user: postgres
    
- name: Start jira
  command: "{{ jira_install }}/bin/start-jira.sh"   
  become: yes

- name: Fetch backup files.
  fetch:
    src: "/tmp/{{item}}"
    dest: ../backup
    fail_on_missing: yes
  with_items:
    - jira_install_backup.tgz
    - jira_home_backup.tgz
    - jira_db_backup.tar
    
