---

- name: Download Exec Jira
  get_url: 
    url: "{{ jira_download_url }}"
    dest: /tmp/{{ jira_exec }}
    owner: root
    group: root
    mode: 0777  
  become: yes
 
- name: Copy Jira Template
  template: 
    src: response.varfile.j2
    dest: /tmp/response.varfile
 
- name: Install Jira
  command: /tmp/{{ jira_exec }} -q -varfile /tmp/response.varfile
  args:
    creates: "{{ jira_home }}"
  become: yes
  
- name: Startup scripts
  include: startup.yml

- name: Copy Jira dbconfig File
  template: 
    src: dbconfig_pg.xml.j2
    dest: "{{ jira_home }}/dbconfig.xml"
    owner: "{{jira_user}}"
    group: "{{jira_group}}"
    mode: 0664
  become: yes
  notify: JIRA service restart

- name: Remove .exe and .bat files from linux install
  file:
    path: "{{ jira_install }}/bin/{{ item }}"
    state: absent
  with_items:
    - catalina.bat    
    - permgen.bat         
    - setenv.bat      
    - stop-jira.bat
    - config.bat      
    - permgenservice.bat  
    - shutdown.bat    
    - tool-wrapper.bat
    - configtest.bat  
    - service.bat         
    - start-jira.bat  
    - version.bat
    - digest.bat
    - setclasspath.bat    
    - startup.bat
    - check-java.bat
    - tomcat7.exe
    - tomcat7.exe.x64
    - tomcat7w.exe
    - tomcat8.exe
    - tomcat8.exe.x64
    - tomcat8w.exe

- name: Remove licenses dir
  file:
    path: "{{ jira_install }}/licenses" 
    state: absent

- name: Remove Notice file
  file:
    path: "{{ jira_install }}/NOTICE"
    state: absent

- name: chown and touch files
  file:
    path: "{{ jira_install }}" 
    owner: "{{ jira_user }}" 
    group: "{{ jira_group }}" 
    recurse: yes
    state: directory
