---
- name: Jira groups
  group: 
    name: "{{ jira_user_group }}" 

- name: Default JIRA user and home
  user: 
    name: "{{ jira_user }}" 
    shell: /bin/bash 
    group: "{{ jira_user_group }}" 
    home: "{{ jira_user_home_dir }}"

- name: Extrat the sources
  unarchive: 
    src: "{{ jira_download_link }}-{{ jira_version }}.tar.gz" 
    dest: "{{ jira_user_home_dir }}"
    copy: no
    creates: "{{ jira_user_home_dir }}/atlassian-jira-{{ jira_version }}-standalone"
    owner: "{{ jira_user }}" 
    group: "{{ jira_user_group }}"     

- name: Make the directory easier to reach
  file: 
    src: "{{ jira_user_home_dir }}/atlassian-jira-{{ jira_version }}-standalone" 
    dest: "{{ jira_user_home_dir }}/jira" 
    owner: "{{ jira_user }}" 
    group: "{{ jira_user_group }}" 
    state: link

- name: Create jira-home dir
  file: 
    path: "{{ jira_home }}" 
    state: directory 
    owner: "{{ jira_user }}" 
    group: "{{ jira_user_group }}" 

- name: Set the home dir inside the configs
  template: 
    src: jira-application.properties.j2 
    dest: "{{ jira_user_home_dir }}/jira/atlassian-jira/WEB-INF/classes/jira-application.properties"
    owner: "{{ jira_user }}" 
    group: "{{ jira_user_group }}" 
    mode: 0644

- name: Copy the service script
  template: 
    src: jira.service.j2 
    dest: /usr/lib/systemd/system/jira.service
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 7

- name: Copy the init.d script
  template: 
    src: jira.j2
    dest: /etc/init.d/jira
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 6
  
- name: Remove .exe and .bat files from linux install
  file:
    path: "{{ jira_user_home_dir }}/jira/bin/{{ item }}" 
    state: absent
  with_items:
    - catalina.bat    
    - permgen.bat         
    - setenv.bat      
    - stop-jira.bat
    - config.bat      
    - permgenservice.bat  
    - shutdown.bat    
    - tool-wrapper.bat
    - configtest.bat  
    - service.bat         
    - start-jira.bat  
    - version.bat
    - digest.bat
    - setclasspath.bat    
    - startup.bat
    - tomcat7.exe
    - tomcat7.exe.x64
    - tomcat7w.exe

- name: Remove licenses dir
  file:
    path: "{{ jira_user_home_dir }}/jira/licenses" 
    state: absent

- name: chown and touch files
  file:
    path: "{{ jira_user_home_dir }}/atlassian-jira-{{ jira_version }}-standalone" 
    owner: "{{ jira_user }}" 
    group: "{{ jira_user_group }}" 
    recurse: yes
    state: directory

- name: Start the jira service
  service:
    name: jira
    state: started
    enabled: yes
